[general]
import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[env]
TERM="xterm-256color"

[font]
size = 13.5

# USE A VERSÃO MONO - CRÍTICO PARA ÍCONES FUNCIONAREM
[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[window]
decorations = "Full"
dynamic_title = false
decorations_theme_variant = "Dark"
class = { instance="Alacritty", general="Alacritty"}
dynamic_padding = true
title = "Alacritty"
dimensions = { columns = 128, lines = 38 }
padding = { x = 5, y = 3}
# blur = true
opacity = 0.90

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard=true

[cursor]
style={shape="Beam", blinking="Always"}
blink_interval=450

[terminal]
shell = "/bin/zsh"
