[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_title = true
decorations_theme_variant = "Dark"
dynamic_padding = true
title = "Alacritty"
startup_mode = "Windowed"
# blur = true
# opacity = 0.95

[window.class]
instance = "Alacritty"
general = "Alacritty"

[window.dimensions]
columns = 128
lines = 38

[window.padding]
x = 5
y = 3

[font]
size = 14

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor]
blink_interval = 450
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[general]
import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"
